#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
process_name="redis"

if var_true ${ENABLE_LOGS} ; then
    mkdir -p ${LOG_PATH}
    touch ${LOG_PATH}/${LOG_FILE}
    create_logrotate redis ${LOG_PATH}/${LOG_FILE} none redis redis
fi

mkdir -p ${DATA_PATH}
chown -R redis:redis ${DATA_PATH}

liftoff