#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
process_name="redis"

mkdir -p ${LOG_PATH}
touch ${LOG_PATH}/${LOG_FILE}
chown -R redis:redis ${LOG_PATH}/${LOG_FILE}
create_logrotate redis ${LOG_PATH}/${LOG_FILE} redis redis redis

if var_true "${ENABLE_SOCKET}" ; then
    mkdir -p ${SOCKET_PATH}
    chown -R redis:redis ${SOCKET_PATH}
    chmod ${SOCKET_PERMISSIONS} ${SOCKET_PATH}
fi

create_zabbix redis

mkdir -p ${DATA_PATH}
chown -R redis:redis ${DATA_PATH}

liftoff