#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service
process_name="redis"

if var_true $ENABLE_LOGS ; then
    mkdir -p /data/logs
    cat <<EOF > /etc/logrotate.d/redis.conf
/data/logs/*.log {
daily
ifempty
rotate 7
missingok
compress
dateext
copytruncate
}
EOF
    chmod -R 755 /etc/logrotate.d/redis.conf
fi

mkdir -p /data/db/
chown -R redis /data

liftoff