#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/99-container-init ]
do
  sleep 1
done

### Set Debug Mode
if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
    set -x
fi

REDIS_PASS=${REDIS_PASS:-}
REDIS_PORT=${REDIS_PORT:-"6379"}
LOG_LEVEL=${LOG_LEVEL:-"notice"}

if [ "$ENABLE_LOGS" = "TRUE" ] || [ "$ENABLE_LOGS" = "true" ]; then
    mkdir -p /data/logs
    cat <<EOF > /etc/logrotate.d/redis.conf
/data/logs/*.log {
daily
ifempty
rotate 7
missingok
compress
dateext
copytruncate
}
EOF
    chmod -R 755 /etc/logrotate.d/redis.conf
    $logs=" --logfile /data/logs/redis.log"
fi    


## Redis Setup
	# first arg is `-f` or `--some-option`
	# or first arg is `something.conf`
	if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
		set -- redis-server "$@"
	fi

	# allow the container to be started with `--user`
	if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
		chown -R redis .
		exec su-exec redis "$0" "$@"
	fi

mkdir -p /data/db/
chown -R redis /data
echo ''
echo '** [redis] Starting Redis'
exec s6-setuidgid redis redis-server --dir /data/db/ \
                                     ${REDIS_PASS:+--requirepass $REDIS_PASS} \
                                     --loglevel $LOG_LEVEL \
                                     --port $REDIS_PORT \
                                     $logs
