version: '3.7'
services:
  
  redis-app:
    image: registry.selfdesign.org/docker/redis/5:latest
    container_name: redis-app
    volumes:
    - ./data:/data/db
    #- ./logs:/data/logs
    environment: 
    - ZABBIX_HOSTNAME=redis-app

    - ENABLE_LOGS=FALSE
    - REDIS_PASS=password
    networks:
    - internal
    - services
    restart: always

networks:
  proxy:
    external: true
  internal:
    external: false
  services:
    external: true

