version: '2'

services:
  redis-app:
    container_name: redis-app
    image: registry.selfdesign.org/docker/redis/5:latest
    volumes:
      - ./data:/data/db
      #- ./logs:/data/logs
    environment: 
      - ZABBIX_HOSTNAME=redis-app

      - ENABLE_LOGS=FALSE
      - REDIS_PASS=password
    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
