#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 10-redis
PROCESS_NAME="redis"

check_container_initialized
check_service_initialized init

liftoff

if var_true $ENABLE_LOGS ; then
    redis_logs=" --logfile /data/logs/redis.log"
fi

if var_true $ENABLE_PERSISTENCE ; then
   redis_persistence="--appendonly yes"
fi

## Redis Setup
	# first arg is `-f` or `--some-option`
	# or first arg is `something.conf`
	if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
		set -- redis-server "$@"
	fi

	# allow the container to be started with `--user`
	if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
		chown -R redis .
		exec su-exec redis "$0" "$@"
	fi

print_info "Starting Redis ${REDIS_VERSION}"
exec s6-setuidgid redis redis-server --dir /data/db/ \
                                     ${REDIS_PASS:+--requirepass $REDIS_PASS} \
                                     --loglevel $LOG_LEVEL \
                                     --port $REDIS_PORT \
				     				${redis_persistence} ${redis_logs}
