#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="redis"

check_container_initialized
liftoff

REDIS_PASS=${REDIS_PASS:-}
REDIS_PORT=${REDIS_PORT:-"6379"}
LOG_LEVEL=${LOG_LEVEL:-"notice"}
ENABLE_PERSISTENCE=${ENABLE_PERSISTENCE:-"TRUE"}

if [ "$ENABLE_LOGS" = "TRUE" ] || [ "$ENABLE_LOGS" = "true" ]; then
    mkdir -p /data/logs
    cat <<EOF > /etc/logrotate.d/redis.conf
/data/logs/*.log {
daily
ifempty
rotate 7
missingok
compress
dateext
copytruncate
}
EOF
    chmod -R 755 /etc/logrotate.d/redis.conf
    $logs=" --logfile /data/logs/redis.log"
fi    

if [ "$ENABLE_PERSISTENCE" = "TRUE" ] || [ "$ENABLE_PERSISTENCE" = "true" ]; then
   PERSISTENCE="--appendonly yes"
fi

## Redis Setup
	# first arg is `-f` or `--some-option`
	# or first arg is `something.conf`
	if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
		set -- redis-server "$@"
	fi

	# allow the container to be started with `--user`
	if [ "$1" = 'redis-server' -a "$(id -u)" = '0' ]; then
		chown -R redis .
		exec su-exec redis "$0" "$@"
	fi

mkdir -p /data/db/
chown -R redis /data

print_info "Starting Redis ${REDIS_VERSION}"
exec s6-setuidgid redis redis-server --dir /data/db/ \
                                     ${REDIS_PASS:+--requirepass $REDIS_PASS} \
                                     --loglevel $LOG_LEVEL \
                                     --port $REDIS_PORT \
				     				$PERSISTENCE \
                                     $logs
